---
title: "Abnormal Schedule Fall 2023"
author: "Brian Holt"
date: "`r Sys.Date()`"
output:
  html_document:
    config:
      search: yes
      toc:
        after: |
          <!-- <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li> -->
        before: |
          <li><a href="./">Abnormal Psychology Fall 2023 schedule</a></li>
        scroll_highlight: yes
      toolbar:
        position: fixed
    css: "style.css"
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
description: This is a minimal example of using the rmarkdown package for abnormal
  psychology
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dagitty)
library(tidyverse)
library(ggdag)
library(tidygraph)
library(ggraph)
```


# Background before we begin

  A. First of all, welcome. My intention is to keep instructions brief and simple. 

  B. You are always welcome to ask for clarification. It is helpful to your instructor if you try to ask the class first because often the class can be helpful. So, please first ask a question in Canvas. If it's personal, please use my email account brian.holt@seattlecolleges.edu

  C. It is absolutely crucial that students, teachers, all of us, respect that everybody comes to this class with different experiences, abilities, and intentions..

  D. It can be embarrassing to ask for help. Please try to ask anyway.  I'll do my best to be thoughtful in reply. 

  E. My intention as the instructor is to teach you ways to evaluate quality knowledge and to practice quality thinking and quality writing. The context of this endeavor is going to be in psychology.

  F. Computer requirements: 

   1. You must have access to a real computer for writing. If you cannot afford a laptop or do not have a laptop or computer please contact me because we actually have free rentals for students. 

   2. A tablet or smartphone will be insufficient. It's fine to do some communication (texting etc) using those tools, but for real writing you're going to need a real computer or a laptop. 
  
  3. You'll need to have quality access to the internet.  IF you don't have consistent access to the internet from home, we have loaner hotspots that you can borrow for free.  They should give you internet at home.
  
G. Software (apps)

  1. A web browser, like firefox, chrome. 

  2. A free Google doc account. If you have Gmail you already have a Google account for documents and spreadsheets. **This is a requirement; no other word processing software will be allowed.** I have reasons and we can talk about them but unless it is related to a disability accommodation you must be using Google docs.

H. Here is the pattern of the course: 

  1. Each week you will be given a list of things to read and it's list of things to do. 
  2. Most of what you'll do is some type of writing assignment in google docs. I will give you instructions and support for how to do this. 
  3. When you have finished the weeks assignment, you will post a link to your work in slack.
  4. Assignments should be submitted in a timely fashion. Friday is the standing due date, with reasonable flexibility. 

`r if (knitr:::is_html_output()) '
# References {-}
'`
