---
title: "Abnormal Schedule Fall 2024"
author: "Brian Holt"
date: "`r  Sys.Date()`"
output:
  html_document:
    config:
      search: yes
      toc:
        after: |
          <!-- <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li> -->
        before: |
          <li><a href="./">Abnormal Psychology Fall 2024 schedule</a></li>
        scroll_highlight: yes
      toolbar:
        position: fixed
    css: "style.css"
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
description: This is a minimal example of using the rmarkdown package for abnormal
  psychology
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---

<!-- if (FALSE) { -->
<!-- # upload a document -->
<!-- result <- rsconnect::rpubsUpload(title="abnormal_schedule", originalDoc="abnormal_schedule.Rmd",contentFile="abnormal_schedule.html") -->
<!-- if (!is.null(result$continueUrl)) -->
<!--    browseURL(result$continueUrl) -->
<!-- else -->
<!--    stop(result$error) -->

<!-- # update the same document with a new title -->
<!-- updateResult <- rsconnect::rpubsUpload("Abnormal_schedule", "abnormal_schedule.html", -->
<!--                             id = result$id) -->
<!-- } -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dagitty)
library(tidyverse)
library(ggdag)
library(tidygraph)
library(ggraph)
```
# Background before we begin

  A. First of all, welcome. My intention is to keep instructions brief and simple. 

  B. You are always welcome to ask for clarification. It is helpful to your instructor if you try to ask the class first because often the class can be helpful. So, please first ask a question in a Canvas Discussion If it's personal, please use my email account brian.holt@seattlecolleges.edu

  C. It is absolutely crucial that students, teachers, all of us, respect that everybody comes to this class with different experiences, abilities, and intentions..

  D. It can be embarrassing to ask for help. Please try to ask anyway.  I'll do my best to be thoughtful in reply. 

  E. My intention as the instructor is to teach you ways to evaluate quality knowledge and to practice quality thinking and quality writing. The context of this endeavor is going to be in psychology.

  F. Computer requirements: 

   1. You must have access to a real computer for writing. If you cannot afford a laptop or do not have a laptop or computer please contact me because we actually have free rentals for students. 

   2. A tablet or smartphone will be insufficient. It's fine to do some communication (texting etc) using those tools, but for real writing you're going to need a real computer or a laptop. 
  
  3. You'll need to have quality access to the internet.  IF you don't have consistent access to the internet from home, we have loaner hotspots that you can borrow for free.  They should give you internet at home.
  
G. Software (apps)

  1. A web browser, like firefox, chrome. 

  2. A free Google doc account. If you have Gmail you already have a Google account for documents and spreadsheets. **This is a requirement; no other word processing software will be allowed.** I have reasons and we can talk about them but unless it is related to a disability accommodation you must be using Google docs.

H. Here is the pattern of the course: 

  1. Each week you will be given a list of things to read and it's list of things to do. 
  2. Most of what you'll do is some type of writing assignment in google docs. I will give you instructions and support for how to do this. 
  3. When you have finished the weeks assignment, you will post a link to your work in a Canvas Discussion.
  4. Assignments should be submitted in a timely fashion. Friday is the standing due date, with reasonable flexibility. 

# Week 1 9/23/24 {#Week1} 

## Read the following

1. [The syllabus](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit?usp=sharing){target="_blank"}

2. [Miller's law of communication (in the syllabus)](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit#bookmark=id.hneoaaz3l9xt){target="_blank"}

3. [George Orwell, Politics and the English Language, 1946 (in the syllabus)](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit#bookmark=id.lcxkb3d2wkmi){target="_blank"}

4. [The 9 standards of Critical thinking (in the syllabus)](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit#bookmark=id.d16shfpyaqlj){target="_blank"}

5. [Textbook, Module 1: What is Abnormal Psychology?](https://opentext.wsu.edu/abnormal-psych/chapter/module-1-what-is-abnormal-psychology/){target="_blank"}

6. Dictionary/Wikipedia definitions on: 

      *Anthropomorphize
 
      *Ethnocentrism

7. **Skim from page 2**, sub heading "The Theory of Knowledge"** of the article: An introduction to Stephen C. Pepper's philosophical system via
_World Hypotheses: A Study in Evidence_**, @berry_introduction_1984 [(found in syllabus) ](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit#bookmark=id.kapuzuy6k04e){target="_blank"}

8. Read about "stereotype threat".  Not stereotypes.  There is a difference.  You'll need to find a source or two on your own.  


```{block,type='blueBackground'}
Some of the links below jump to the references section at the end of this document.  From there, you may find links to the actual article or you will have references to fetch from our college's library databases.  
```
<br />  

9. [Module 2: Models of Abnormal Psychology](https://opentext.wsu.edu/abnormal-psych/chapter/module-2-models-of-abnormal-psychology/){target="_blank"}

10. [Diathesis stress video youtube](https://www.youtube.com/watch?v=1MaaORgCHvc){target="_blank"}

```{block, type='instructorNote'}
Please have the following readings below, @efran_defining_2007, @szasz_myth_1960, and @@watters_americanization_2010  read by Thursday of week 2 (October 3) so that we can discuss in class.
```


11. @efran_defining_2007 (to obtain this article, you'll need to walk through the steps found in the [Using the Library section down below in the appendix](#useLibrary) --in particular the [Periodical Locator](#PeriodicalLocator))

  * I want students to read the 'how to use a library' section, but I can admit that students may not want to.  The crux of finding this particular article is found in the following steps: [How to find an article](#libraryMainPoint).
    
<br>  

12. @szasz_myth_1960  which can be found using this link [Szasz link to web](http://psychclassics.yorku.ca/Szasz/myth.htm){target='_blank'}

13. Americanization of Mental Illness @watters_americanization_2010 which [can be found in our syllabus by clicking this link](https://docs.google.com/document/d/1Xz6lc6qURPmLZ7o-upBlkgqhIJJUwkO6faZKIvHXbM8/edit#bookmark=id.a11215pgy49s){target='_blank'}



## Do the following

1. Introduce yourself the [Canvas Discussion Introductions discussion](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/286687){target="_blank"}

2. Write something about what interests you about Abnormal psychology in your one google doc. Be sure to give it a title.  You can also insert a page break between your writings.  

3. On the same google document, make a new page, title it, and write some thoughts down to the following prompts.  When you are done, post to the [Week 1 Canvas Discussion ](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/284353){target="_blank"}.

    *   What is your process for thinking clearly?

    *   How do you know something is true?
    

4. Read some of your classmates' posts and comment on some. 

6. When you are done, create a link to your work: highlight the title of your assignment and then go to the "Insert" menu of google. In that menu, find "bookmark" and select that. Your title is now a bookmark and if you hover over it, you should see a little 'link' option.  Copy that link and post it in the  [Week 1 a Canvas Discussion](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/284353){target="_blank"}.




7. Read a few other students and make some comments on their post.   Use google docs to make these comments.  Highlight any part of their document and you can insert a comment. you can click and use the menu, or you can use the keyboard shortcut 'ctrl + alt +m'


8. Please fill out this [Importance of Sexuality Survey](https://docs.google.com/forms/d/e/1FAIpQLSfpnmmTRSjBNa50tTLHsUX3venfF8aTe85CCXVha6cFeO_Sew/viewform?usp=sf_link){target='_blank'}.  It is anonymous. I do not collect information that can be personally tied to you. If you are logged into your google account, google will show you your email address and say that you can use your account to 'store' your work so that you can come back to it. But that's google and not the survey.  I don't track your email.

* It's not required, but it's helpful for my classes because it is useful to see how surveys are supposed to work. 



# Week 2 Sept 30 {#Week2} 

## Read the following

* [Module 3: Clinical Assessment, Diagnosis, and Treatment](https://opentext.wsu.edu/abnormal-psych/chapter/module-3-clinical-assessment-diagnosis-and-treatment/){target="_blank"}


* Not So Fast, a comment to Riskind about diagnostic schemes. @efran_not_2019  * [link to file](https://scedu-my.sharepoint.com/:b:/g/personal/brian_holt_seattlecolleges_edu/ETCu0ddUA9hMqPKSwD2kdF8Bv_gW0BW57BTy984t8fB7vg?e=8OXmZe){target='_blank'}


* [Instructor Lecture Intro to Epidemiology](https://youtu.be/eUYIwNChS0I){target='_blank'}

* [Instructor Lecture Epidemiology Example](https://youtu.be/XQoH5avTlzA){target='_blank'}

* Intro to alternative to DSM
  * [Video on Psychodynamic Diagnostic Manual](https://scedu-my.sharepoint.com/:v:/g/personal/brian_holt_seattlecolleges_edu/EZNoUFHoBuNHh9-8MlFyapoB3488qemw_ZuAK28sgV0gWQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=wHmZlm){target='_blank'}.

  * [Skim Excerpts of Chapter 1 and 2 from PDM2 @lingiardiPsychodynamicDiagnosticManual2015a](https://scedu-my.sharepoint.com/:b:/g/personal/brian_holt_seattlecolleges_edu/ETDxh7RV-ZBFmMvr8ep8SBwBW14Gi259giuf97xfjpe0vw?e=dZK5FH){target='_blank'}   
     * In particular the Table on mental functioning
  * [Skim Example Personality disorders from PDM2](https://scedu-my.sharepoint.com/:b:/g/personal/brian_holt_seattlecolleges_edu/EbZq3TqBpsBFp8efwadnKEQBHi0UB1hUtE5oB5lv3VJjXA?e=nML8n0){target='_blank'}  
  
After reading/watching the above...

## Do the following

### From Last week

0. synthesize @efran_defining_2007 , @szasz_myth_1960, and @watters_americanization_2010.  When synthesizing, don't summarize the articles. You may assume that your audience is your class, which means they should be familiar with those articles.  Instead of summarizing, let you references to their work so you can do yours.  
<br />  
    * [Lecture on one way to write a synthesis paper--This should pop-up a new tab/window but you'll have to log in to canvas because that is how the videos are stored.](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=44737fc2-c8cb-4286-9dcf-ac4b011de256){target='_blank'}
<br />  



## This week

1. In the one document to rule them all, write about which psychology Model from [Module 2: Models of Abnormal Psychology](https://opentext.wsu.edu/abnormal-psych/chapter/module-2-models-of-abnormal-psychology/){target="_blank"} resonates with you and why---Yes you may have skimmed this for week 1.

2.  Ask chatGpt what makes a good diagnostic system. Start in the abstract. Ask it about "criteria". Keep on the lookout for terms like "specificity" and "sensitivity".  From here, find some questions in it's responses and ask it to elaborate, to challenge it. Share your questions in your one google doc.

3. In your google doc, write a short essay about what you learned from chatGpt and any other source regarding diagnostic decision making. 

4. Lastly, in the one document to rule them all, list some questions about the readings/content for this week. Things you would like to learn more about. 

5. Post to [#week2--notice this is a clickable link](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/287149?module_item_id=1379717){target="_blank"}


# Week 3 Oct 7 {#Week3} 

Please first fill out this anonymous survey on how many hours you spent on class during LAST week: [Survey on week 2  workload](https://docs.google.com/forms/d/e/1FAIpQLSeNVXfXLd5_XHqLlom99JZ8U8KMrlg5XbRjYdhRGkd98WlygQ/viewform?usp=sf_link){target="_blank"}



## Read/watch the following

* [Module 7: Anxiety Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-7-anxiety-disorders/){target="_blank"}

* [humanistic intro](https://www.youtube.com/watch?v=KDRHaL6jyg8&list=PLDEwZwMNQswvPj4onxTjBdXgzFYJ6G-JJ&index=5){target="_blank"}

* [first 3 videos of this youtube playlist on biopsych](https://www.youtube.com/playlist?list=PLDEwZwMNQswtFvhRvOliHzeDfuBPIdsSf){target="_blank"}

* Video [Introduction to Existential psychology](https://youtu.be/6eXnVhsz5qE){target='_blank'}, emphasis on @Yalom_Existential_Psychotherapy_1980


## Do the following

* Pick an Anxiety disorder form the following: 
  +  panic
  +  phobia
  +  social anxiety disorder
  +  generalized anxiety Disorder

  * and find 2 articles that suggest what causes it
    * The article should be from either these two school databases:
      * [Academic Search Complete](https://libguides.northseattle.edu/az.php?a=a){target="_blank"}
      * [PsychArticles](https://libguides.northseattle.edu/az.php?a=p){target="_blank"}

* Write 1 or 2 paragraphs about what you have learned into your google doc.  This does not necessarily mean you should summarize the journal articles you found. This is a reflective piece.  Write about the questions you have or where your mind goes.

* Post a link in the [#week3 Discussion in canvas](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/289362){target="_blank"} 

s* Read 3 other student's work and engage them on their submission--you can ask them questions as an example. 


# Week 4 Oct 14 {#Week4} 


## MetaCognition

To begin, and before you start doing more reading and writing, I want you to first imagine some scenario. Maybe it’s simple like watching a bird. Maybe you can do it right now as you read these instructions.  If you want to write it in your google document, you can.  But you don't have to. 



While you do this, imagine that you are able to witness your thoughts from the point of view of another person, or perhaps a different side of yourself.

>“So, I can see myself, Brian, sitting at his computer writing these words and I notice that Brian looks up at the window and appreciates the leaves in the sun on the Rhododendron outside this room; it was around then that Brian thought to use ‘watching a bird’ as a part of the assignment. He also felt a little like he’d rather be out in the sun but a lot of people need him to finish this. Brian also considered not including that last sentence.”

It might be that you are watching your behavior and then noting the pattern of how/where your thoughts come about; it might be an auditory exercise where you’re able to listen and hear the words you’re saying. Most of you do this naturally, but some of you might not have a lot of experience in observing your own thoughts. This is a meta cognitive exercise.

## Do, Watch, and Read the following

A. Read [Module 5: stress Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-5-trauma-and-stressor-related-disorders/){target="_blank"}

B. Read Nancy Chick, [Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/){target="_blank"}

C. Read Alfie Kohn, [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/){target="_blank"}

D. Read Booth et al. Craft Of Research excerpt, just below in blue @boothCraftResearch2016.  Notice the metacognitive aspects


```{block,type='blueBackground'}
<h2 style="text-decoration: underline;">Craft of Research Excerpt</h2>
<h4 style="text-decoration: underline;">Why write our research up?</h4>

For some of you, the invitation to join into a expert research conversation may still seem easy to decline but if you accept it you'll 

One answer is that we write not just to share our work but to improve it before we do.

<h4 style="text-decoration: underline;">Why write our research up?</h4>

For some of you, the invitation to join into a expert research conversation may still seem easy to decline but if you accept it you'll have to find a good question, search for sound data, formulate and support a good answer and then write it all up and even if you turn out a first-rate paper, it may be read not by anyone in the world but only by your teacher. And besides, you may think, my teacher knows all about my topic. What do I gain from writing up my research, other than proving I can do it?

One answer is that we write not just to share our work but to improve it before we do.

<h4 style="text-decoration: underline;">Write to remember</h4>

Experienced researchers first write just to remember what they read. A few talented people can hold in mind masses of information, but most of us get lost when we think about what *Smith found in light of Wong's position, and compare both to the odd data in Brunelli, especially as they are supported by Buscovich but what was it that Smith said?* When you don't take notes on what you read, you are likely to forget or, worse misremember it.

<h4 style="text-decoration: underline;">Write to understand</h4>

The second reason for writing is to see larger patterns in what you read. When you arrange and rearrange the results of your research in new ways, you discover new implications, connections, and complications. Even if you could hold it all in mind, you would need help to line up arguments that pull in different directions, plot out complicated relationships, sort out disagreements among experts. 

*I want to use these claims from long, but her argument is undercut by Smith's data. When I put them side-by-side, I see that Smith ignores this last part of Wong's argument. aha! If I introduce it with this part from Brunelli, I can focus on one more clearly. *

That's why careful researchers never put off writing until they've gathered all the data they need: they write from the start of their projects to help them assemble their information in new ways. 

<h4 style="text-decoration: underline;">Write to test your thinking</h4>

But even when they agree that writing is an important part of learning thinking and understanding some still wonder why they can't write up their research in their own way, why they have to satisfy demands imposed by a community that they have not joined, or even want to, and conform to conventions they did nothing to create. 

*Why should I adopt language in forms that are not mine? Aren't you just trying to turn me into an academic light yourself? If I write as you expect me to, I risk losing my identity.*

Such concerns are legitimate (most teachers wish students would raise them more often). But it would be a feeble education that did not change you at all, and the deeper your education the more it will change the "you" that you are or want to be.

That's why it is so important to choose carefully what you study and with whom. But it would be a mistake to think that learning to report sound research must threaten your true identity. It will change the way you think, but only by giving you more ways of thinking. You will be different by being freer to choose who you want to be and what you want to do with your life. 

But the most important reason for learning to write in ways readers expect is that when you write for others, **you demand more of yourself and when you write for yourself alone.** By the time you fix your ideas in writing, they are so familiar to you that you need help to see them not for what you want them to be *but for what they really are.* 

You will understand your own work better when you try to anticipate your readers inevitable and critical questions: how have you evaluated your evidence? Why do you think it's relevant? What ideas have you considered but rejected?
```





## Do the following

1. Search for 3 reasonably competent definitions of trauma, but avoid the DSM.  You can use the DSM as a 4th source for contrast, if you want. Include references and do a quick summary/description of what you found. 
2. In the same document, how would you defend the statement:

>Everyone goes through trauma.

3. Post your paper in the disucssion [#week4](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/291480){target="_blank"}

# Week 5 Oct 21 {#Week5} 

Please first fill out this anonymous survey on how many hours you spent on class during LAST week: [Survey on Last week, week 4  workload](https://docs.google.com/forms/d/e/1FAIpQLSdgRU-wmHhqC4vUfZYwyFAa991_DzXw4bpwlj7On6Cr51XoiA/viewform?usp=sf_link){target="_blank"}


## Read the following

a. Read/skim [Primer for Behaviorism and Semantic networks](https://docs.google.com/document/d/1MMziOQh7NjWRnrzCZDT99ArOu8Nv6CzQfTEfbSCzjYA/){target="_blank"}

* skim this but pay closer attention the semantic sections with the schematics for cars
* Think of a subject.  Maybe it's something academic like math, biology.  Maybe it's about sports, or in particular a single sport, like (the only one that matters) basketball.  
   * in what specific ways would the semantic network be different between a novice and expert?  I don't expect you to know technical terms here (like nodes, edges) but I want you to have an appreciation for how people may differ in terms of their networks

D. [Module 9: Obsessive and Hoarding disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-9-obsessive-compulsive-and-related-disorders/){target="_blank"}

## Do the following

 1. Pick one of the disorders in the OCD module: 
  
  * and find 2 articles that discusses its cognitive pattern
    * The article should be from either these two school databases:
      * [Academic Search Complete](https://libguides.northseattle.edu/az.php?a=a){target="_blank"}
      * [PsychArticles](https://libguides.northseattle.edu/az.php?a=p){target="_blank"}

 2. Write a page about what you have learned. Write a summary, but write as if you were writing it to a non-technical person that doesn't understand cognitive psychology.  

 3. post a link in the [#week 5 canvas discussion](https://canvas.seattlecolleges.edu/courses/27182/discussion_topics/293278){target='_blank'}
 
 4. Pick 2 other students and invite them to read your post. How? Well, I think canvas now allows "tagging".  Once you have pasted your link, but before submitting, you can type the '@' symbol and that should provide you with a drop down list of classmates to choose from. 
 
 In the invitation, think about what you might like to receive some feedback about. 
 
  * Invite people to help you on any of the critical thinking standards, for example. 
  * if you are invited to give feedback, you don't have to.  Sometimes you might have several people asking for feedback.  Don't feel like you must respond to all of them.

    Should you chose to give feedback, be kind and try to adhere to the request. 
  * Remember that they are trying things out and are sharing potentially vulnerable parts of their lives.  If you need help giving feedback, send your instructor a /dm and I can help.
  * Also, because everything is just hard, don’t fret if people you invite can’t respond. It’s likely that they are just overwhelmed with something.    
    
<p>
<p>

5. Another Sexual information questionnaire:  [Sexual Assertiveness](https://docs.google.com/forms/d/e/1FAIpQLSfCHJDqjWxvaJZRBZYdZL_TjbDyZG_4XGwgNebWbzaPwIY2Pg/viewform){target='_blank'}

    -Like before, it's optional an anonymous.  But because I found errors in my Human Sexuality textbook, I'd like to provide better information to my students while learning a bit about our community college population



# Appendix

## Using the library {#useLibrary} 

The library has set up a simple library guide for our class.  You can find it here: [Abnormal Psychology library guide](https://libguides.northseattle.edu/psych220). I

```{block, type='blueBackground'}
<span class='sidenote'>Note: Don't pay for articles</span>

One important word of advice is to never pay for a scholarly article. If you go online and use Google, or even Google Scholar to find online sources, you may be directed to the publication that will charge you a large amount of money to access just one article.  So don’t do that.

Generally there are ways to get articles through our library, so don't pay for articles.
```


To get started with our readings, you'll need to use our Library (online, of course) to obtain many of the articles.  

Finding journal articles is a skill that gets better with practice.  This happens to be why Librarians are so helpful.  They've actually been trained so if you can't find an article, it's okay to ask librarians for help.  

In fact, here is how you can [get help from North Seattle's library staff](https://libguides.northseattle.edu/welcome/askus). 



### Relationship of an article to its Journal

Using hierarchies helps us organize information. Journal articles, or for that matter the file directories on your computer, work somewhat like an address for a person's home. There are several different parts that give us information to track down and locate whatever it is we're looking for, be it a computer file, or Journal article. Basically, a journal article  has the following components, some of which may be familiar to you :

      Database (of periodicals)
        Periodical (eg., magazine, newspaper, scholarly journal)
         Year (of publication)
           Volume Number
            Volumne Issue number
             Page Number (optional, often unnecessary)
               Article Title
                  Author

So, to find an article, you'll need to know the parts above.  When you are given a list of references, or citations, nearly all of the information needed above is given to  you.  What is not given, or at least is done implicitly with web searches, is access to the top part, the database.  

#### Here is a typical citation:

>Author(s). (year of pub). "Article Title." <span class='underline'>Periodical title</span>. Volume Number (issue number).

The information in a citation isn't presented in the same hierarchy as above, but all of the necessary parts are there.  

Here is an example citation (reference) for something we may read.  Can you identify the periodical?

>Jay Efran, Michael Lukens, Mitchell Greene. 2007. “Defining Psychotherapy: The Last 25 Years Have Taught Us That It’s Neither Art nor Science.” <span class='underline'>Psychotherapy Networker</span> 31 (2). 

Most of the items in the list above are self-explanatory. I want to focus a bit about periodicals.

```{block, type='blueBackground'}
<span class='sidenote'>Note on formatting citations: underlining publication titles</span>

In print, publication titles are *italicized*.  I have a very hard time noticing that subtle font.  

When you submit a written manuscript for printing, publication titles are <span style='text-decoration: underline'>underlined</span> because traditionally manuscripts were typed with typewriters, and to be able to type italicized words required an entire additional alphabet represented in the hammers.  So, underlining was how you could emphasize a word, and the printer--a physical person--could notice the author's formatting intent and correctly publish the final product in italics. 

It's a bit different now with our computers, obviously.  Still, I have a hard time seeing italicized words and will occasionally use underline. 

So, sometimes I'll underline pub titles, sometimes I'll italicize. I have no rule on this.  I am chaos manifested.  Beware. 
```

#### Periodicals

These are just the names of the major publication. _The New York Times_, is colloquially known as a newspaper but technically it is a periodical. <span class='underline'>The Journal of Abnormal Psychology</span> is also a periodical. 

When we search for articles, we have to first know which journal, or periodical, owns that article.  So it is a little counter intuitive but once we have identified an article we would like to read, we have to first find out whether or not our College has access to that periodical.  

To do that, we have to use our colleges periodical locator.

### Finding a journal using Periodical locator

#### Periodical locator {#PeriodicalLocator} 

Notice the first link within [North's Article page](https://libguides.northseattle.edu/welcome/articles){target="_blank"}.  It should say "Periodical Locator"

There are many databases, inside of these databases are pages of journals, and inside those journals are articles. 

**We need to use the periodical locator to determine which database houses which periodical.  With that, we can then open up that periodical and get the article**


```{block, type='blueBackground'}
<span class='sidenote'>Note on 'free' articles and tuition/fees</span>

Part of the fees that you pay as a student are used to pay subscriptions for these periodical databases. We have a small, but pretty good selection. Major universities have much larger collections due to their size and tuition/fee structure.

So in a way, you are **not** actually getting this for free because you are paying for library access. That's the benefit of taking classes from a college. If you were not an active student, you would not be able to see many of these articles.

So, download them all!
```

##### Here's the main point: {#libraryMainPoint} 

I've given you a list of Articles to read. To read them, you must first find them; some will be out in the internet, some will be in our schools' databases. So, use the information I've given you to find out which location (database, Wikipedia, Google, Google scholar) you'll need to search to obtain the full article. You will start by using the periodicals locator tool.

Let's use that @efran_defining_2007 article.  

1. Go to  [North's Article page](https://libguides.northseattle.edu/welcome/articles) and click on the periodical locator.  

2. Type in the name of the periodical for Efran's piece. 

You will see a link with the periodical's name.  Go ahead and click on this but beware of the next instruction:

3. Once you have clicked on that link you may want to start searching within that publication. But do not do that. Instead, notice a little bit further down the search box you should see something that says "View online" and beneath that you should see something that says "proquest research library".   It’s this piece we need.

    That Proquest research library is the database that you've all paid fees to access. So you need to remember that database name.  Or, I think now you can just click on it and skip to step 8.

4. While remembering that database name, you need to go back to  [North's Article page](https://libguides.northseattle.edu/welcome/articles).

5. Notice what is presented here.  You can see Periodical locator, but notice "A to Z" list of databases.  (You might also notice just below two links; one to academic search and the other to Proquest).



6. Click on "A to Z"

7. You might notice that there are 67 databases that North Seattle has premium access to. In our case we're going to be looking for the proquest direct database. And we can either click on the letter "P" or we can just type in proquest direct.


```{block, type='blueBackground'}
<span class='sidenote'>Note on Popular sources</span>

You may also notice the little tag "popular" next to proquest link.  That's an indicator that the articles are not peer reviewed and so aren't exactly cutting edge science. Even though this particular journal we are looking for, _Psychotherapy Networker_, is flagged as a popular type, it is a place for therapists to share their thoughts on the profession so there is a lot of value in it.

For help in distinguishing the different types of sources, the library has some guides:

* [Scholar vs popular](http://libguides.northseattle.edu/c.php?g=97441&p=630690)

* [Find Scholarly Journals](http://libguides.northseattle.edu/c.php?g=97441&p=630669)

```

8. Opening Proquest from your home, or remotely, you will need to validate your credentials. In other words, you need to prove that your are in fact a student of North Seattle before you can continue, which is why you've been prompted for your @ seattlecolleges.edu email and password. Once you do that you'll then be able to see inside of the proquest database. Then you can now search for the article.

     - 8a. If you don't know your @ seattlecolleges.edu email, or email password, you can go to this location [https://tools.seattlecolleges.edu/Initialize/resetmypassword](https://tools.seattlecolleges.edu/Initialize/resetmypassword){target='_blank'} to update it, reset/change the password. If you still can't get access, let me know.
<p>     </p>
9. You should see a simple search box, where you can enter important bits of information. I often start with the author's last name, in this case, Efran,and then some unique identifying feature of the article. A few key words of the article title, or perhaps the full article title will be useful.

But notice that next to the text boxes there are drop down menus. You need to use those, otherwise the search engine will just search for your terms anywhere in the document and will provide too many 'hits'. Instead, you should indicate ‘Efran’ as author, and "defining" in the document title. (of course, you could search any way you like).

When you search for those two terms in their respective fields, you will get two hits and one of them is the article we need. You should notice that it is a full text, not all databases provide full text documents. But in this case it's a full text. You can either print it or read it online.

Yay.  Now you can find the other articles. 

### A quick video of the process (some day once ctclink matures)

## Anatomy of a journal article

#### Title
#### Abstract
#### Introduction
##### Lit review
##### hypothesis
#### Methods
##### Participants
##### Materials
##### Procedure
#### Results
#### Discussion
#### References




`r if (knitr:::is_html_output()) '
# References {-}
'`
