---
title: "Week 6"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---


# Week 6 Oct 30 {#Week6} 

```{block, type='instructorNote'}
On Wednesday, Nov 1, there will be no classes held for the whole school District.  

Faculty are expected to be doing other college work.  

Which means none of you can be required to attend any class on 11/1.  For any class.  In the whole Seattle college district.  
```


## Read the following

a. Read/skim [Primer for Behaviorism and Semantic networks](https://docs.google.com/document/d/1MMziOQh7NjWRnrzCZDT99ArOu8Nv6CzQfTEfbSCzjYA/){target="_blank"}

* skim this but pay closer attention the semantic sections with the schematics for cars
* Think of a subject.  Maybe it's something academic like math, biology.  Maybe it's about sports, or in particular a single sport, like (the only one that matters) basketball.  
   * in what specific ways would the semantic network be different between a novice and expert?  I don't expect you to know technical terms here (like nodes, edges) but I want you to have an appreciation for how people may differ in terms of their networks

D. [Module 9: Obsessive and Hoarding disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-9-obsessive-compulsive-and-related-disorders/){target="_blank"}

## Do the following

 1. Pick one of the disorders in the OCD module: 
  
  * and find 2 articles that discusses its cognitive pattern
    * The article should be from either these two school databases:
      * [Academic Search Complete](https://libguides.northseattle.edu/az.php?a=a){target="_blank"}
      * [PsychArticles](https://libguides.northseattle.edu/az.php?a=p){target="_blank"}

 2. Write a page about what you have learned.  Write a summary, but write as if you were writing it to a non-technical person that doesn't understand cognitive psychology.  

 3. post a link in the [#week6 Canvas Discussion](https://canvas.seattlecolleges.edu/courses/16722/discussion_topics/164746){target='_blank'}

 4. Pick 2 other students and invite them to read your post. In the invitation, think about what you might like to receive some feedback about. 
    * Invite people to help you on any of the critical thinking standards, for example. 
    * if you are invited to give feedback, you don't have to.  Sometimes you might have several people asking for feedback.  Don't feel like you must respond to all of them.  
    Should you chose to give feedback, be kind and try to adhere to the request. 
    * Remember that they are trying things out and are sharing potentially vulnerable parts of their lives.  If you need help giving feedback, send your instructor a /dm and I can help.
    * Also, because it’s still the pandemic and everything is just hard, don’t fret if people you invite can’t respond. It’s likely that they are just overwhelmed with something.    
<p>
<p>
5. Another Sexual information questionnaire:  [Sexual Assertiveness](https://docs.google.com/forms/d/e/1FAIpQLSfCHJDqjWxvaJZRBZYdZL_TjbDyZG_4XGwgNebWbzaPwIY2Pg/viewform){target='_blank'}

    -Like before, it's optional an anonymous.  But because I found errors in my Human Sexuality textbook, I'd like to provide better information to my students while learning a bit about our community college population



`r if (knitr:::is_html_output()) '
# References {-}
'`