---
title: "Week 10"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---


# Week 10 Personality Dis. Nov 27 {#Week10} 

Make notice of the last week [final Project](https://docs.google.com/document/d/11GxIlOTqrcXQ-MlW9eikqR-dH_ErgsjCv8xu0Zj5S60/edit){target="_blank"}.  I would recommend starting that, or at least putting in your list of things to do sooner than later.  

## Read/watch

[Textbook personality Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-13-personality-disorders/){target='_blank'} #make note of the therapy options for Borderline

* [PDM on Personality levels](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8d9d4140-098d-45c5-ae91-abd7013ff9f0){target='_blank'}  #this and the next few links will take you to panopto or slack
  1) supporting file [Levels of organization](){target='_blank'}
  2) supporting file [Personality Disorder examples from PDM](){target='_blank'}

* read [@westenEfficacyDialecticalBehavior2000]  [link to source in library...I'm not sure it will work because I'm linking to the psychArticles database](https://northseattle.idm.oclc.org/login?url=https://search.ebscohost.com/login.aspx?direct=true&db=pdh&bquery=AU+westen+AND+TI+dialectical+behavior+therapy&type=1&searchMode=Standard&site=ehost-live){target='_blank'}  
      * if this link doesn't work, it can be found in the psychArticles database found in North's Library journal page.
  * Note the date
  * For 2.5 pages it is dense. Jot down 2 major ideas.  You may need summarize in your own words to step up and above the details.  
  * Make a few notes on the motivation of the author
 
* [follow up study example](https://acamh.onlinelibrary.wiley.com/doi/full/10.1111/jcpp.13077?casa_token=mOamZoqXZS4AAAAA%3A1srQWWBtGfy14Zt2imV1539TfVzoDefV8wgNPwmck7xR_z1vQEscq9U3Y8_s16E2mrs_7ZfX5Qwlra7ejg){target="_blank"}


## Do

* Recall the 4 D's.  Write a response to the following:  In diagnosing a personality disorder what are some obstacles and or features to consider to differentiate them from healthy personalities? 

* If you want, I'd love to read articles that have a follow up analysis more than 6 months on DBT effectiveness.  (So, the study on therapy concludes with participants having something like more than a 2 month follow up.  I'm looking for something more than 6 months.  Longer is better, but much harder to do and therefore find.)

* Post to  [#week10 discussion](https://canvas.seattlecolleges.edu/courses/16722/modules/items/780096){target="_blank"}



`r if (knitr:::is_html_output()) '
# References {-}
'`