---
title: "Week 5"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---

# Week 5 Oct 23 {#Week5} 

## MetaCognition

To begin, and before you start doing more reading and writing, I want you to first imagine some scenario. Maybe it’s simple like watching a bird. Maybe you can do it right now as you read these instructions.  If you want to write it in your google document, you can.  But you don't have to. 



While you do this, imagine that you are able to witness your thoughts from the point of view of another person, or perhaps a different side of yourself.

>“So, I can see myself, Brian, sitting at his computer writing these words and I notice that Brian looks up at the window and appreciates the leaves in the sun on the Rhododendron outside this room; it was around then that Brian thought to use ‘watching a bird’ as a part of the assignment. He also felt a little like he’d rather be out in the sun but a lot of people need him to finish this. Brian also considered not including that last sentence.”

It might be that you are watching your behavior and then noting the pattern of how/where your thoughts come about; it might be an auditory exercise where you’re able to listen and hear the words you’re saying. Most of you do this naturally, but some of you might not have a lot of experience in observing your own thoughts. This is a meta cognitive exercise.

## Do, Watch, and Read the following

A. Read [Module 5: stress Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-5-trauma-and-stressor-related-disorders/){target="_blank"}

B. Read Nancy Chick, [Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/){target="_blank"}

C. Read Alfie Kohn, [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/){target="_blank"}

D. Read Booth et al. Craft Of Research excerpt, just below in blue @boothCraftResearch2016.  Notice the metacognitive aspects


```{block,type='blueBackground'}
<h2 style="text-decoration: underline;">Craft of Research Excerpt</h2>
<h4 style="text-decoration: underline;">Why write our research up?</h4>

For some of you, the invitation to join into a expert research conversation may still seem easy to decline but if you accept it you'll 

One answer is that we write not just to share our work but to improve it before we do.

<h4 style="text-decoration: underline;">Why write our research up?</h4>

For some of you, the invitation to join into a expert research conversation may still seem easy to decline but if you accept it you'll have to find a good question, search for sound data, formulate and support a good answer and then write it all up and even if you turn out a first-rate paper, it may be read not by anyone in the world but only by your teacher. And besides, you may think, my teacher knows all about my topic. What do I gain from writing up my research, other than proving I can do it?

One answer is that we write not just to share our work but to improve it before we do.

<h4 style="text-decoration: underline;">Write to remember</h4>

Experienced researchers first write just to remember what they read. A few talented people can hold in mind masses of information, but most of us get lost when we think about what *Smith found in light of Wong's position, and compare both to the odd data in Brunelli, especially as they are supported by Buscovich but what was it that Smith said?* When you don't take notes on what you read, you are likely to forget or, worse misremember it.

<h4 style="text-decoration: underline;">Write to understand</h4>

The second reason for writing is to see larger patterns in what you read. When you arrange and rearrange the results of your research in new ways, you discover new implications, connections, and complications. Even if you could hold it all in mind, you would need help to line up arguments that pull in different directions, plot out complicated relationships, sort out disagreements among experts. 

*I want to use these claims from long, but her argument is undercut by Smith's data. When I put them side-by-side, I see that Smith ignores this last part of Wong's argument. aha! If I introduce it with this part from Brunelli, I can focus on one more clearly. *

That's why careful researchers never put off writing until they've gathered all the data they need: they write from the start of their projects to help them assemble their information in new ways. 

<h4 style="text-decoration: underline;">Write to test your thinking</h4>

But even when they agree that writing is an important part of learning thinking and understanding some still wonder why they can't write up their research in their own way, why they have to satisfy demands imposed by a community that they have not joined, or even want to, and conform to conventions they did nothing to create. 

*Why should I adopt language in forms that are not mine? Aren't you just trying to turn me into an academic light yourself? If I write as you expect me to, I risk losing my identity.*

Such concerns are legitimate (most teachers wish students would raise them more often). But it would be a feeble education that did not change you at all, and the deeper your education the more it will change the "you" that you are or want to be.

That's why it is so important to choose carefully what you study and with whom. But it would be a mistake to think that learning to report sound research must threaten your true identity. It will change the way you think, but only by giving you more ways of thinking. You will be different by being freer to choose who you want to be and what you want to do with your life. 

But the most important reason for learning to write in ways readers expect is that when you write for others, **you demand more of yourself and when you write for yourself alone.** By the time you fix your ideas in writing, they are so familiar to you that you need help to see them not for what you want them to be *but for what they really are.* 

You will understand your own work better when you try to anticipate your readers inevitable and critical questions: how have you evaluated your evidence? Why do you think it's relevant? What ideas have you considered but rejected?
```





## Do the following

1. Search for 3 reasonably competent definitions of trauma, but avoid the DSM.  You can use the DSM as a 4th source for contrast, if you want. Include references and do a quick summary/description of what you found. 
2. In the same document, how would you defend the statement:

>Everyone goes through trauma.

3. Post your paper in the [#week5](https://canvas.seattlecolleges.edu/courses/16722/discussion_topics/162255){target="_blank"}



`r if (knitr:::is_html_output()) '
# References {-}
'`