---
title: "remaining weeks"
author: "Brian Holt"
date: "`r Sys.Date()`"
output:
  html_document:
    config:
      search: yes
      toc:
        after: |
          <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
        before: |
          <li><a href="./">Abnormal Psychology Fall 2020 schedule</a></li>
        scroll_highlight: yes
      toolbar:
        position: fixed
    css: "style.css"
    number_sections: no
    toc: yes
    toc_depth: 6
    toc_float: yes
description: This is a minimal example of using the rmarkdown package for abnormal
  psychology
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Getting started {#getStart} 

## Course Layout

Read/watch some things, write some things.  You will save these written bits of work saved in a Google doc.  Microsoft documents are too complicated (I can explain if you are interested),

### ungrading and self reflections

Could rubrics and point chasing be harmful.  Or at worst they don't foster good thinking and education.  I am realizing that using them reduce anxiety in me, the instructor, because I don't have to actually consider the student.  

An overview video on self reflection.  This is not a detailed set of instructions but a gentle intro. [self refleciton overveiw](https://youtu.be/rsH09jsGVSk){target='_blank'}


### Grades 

Grades will be based on your own assessment of what you've earned. You are giving yourself a grade. I have the right to overrule your assessment, but I anticipate people are going to be fair to themselves to this class. Feedback will be given to many of your weekly writings. However I do not promise to give feedback to all papers every week.

I intend to provide my own writing each week and my own reflection for you to witness. If I do give you feedback on a weekly writing, my intention for it is to push gently for you to consider deeper issues that is aligned with your wants for the class. If I give you feedback on a weekly assignment, the feedback will be embedded in your document. This is why I have asked you to allow anyone with the link to edit.  My hope is to just put comments right into your doc.

At least twice this quarter I will ask you to provide me a short sample of your writing from the previous weeks and a self-reflection on your progress. I will read all of these and give feedback on all of them.

The reason you're writing every week is to provide yourself a track record of writings from which you can reflect upon. If you do not do this, you won't have enough papers to reflect upon.

###  Communication

#### Canvas will be used lightly.

First week discussions and introductions, a place to find this schedule, and a way for me to quickly send announcements.

#### Please don't use Canvas as email

#### Use discussion boards in slack

First of all, you may have some questions about Slack.

It's basically a social media platform where you can participate in teams by having threaded chats or sharing of documents.It can be used synchronous synchronously or asynchronously.

The main reason I'm using it is simply that canvas does not have the same capabilities. It also requires a lot more work for me as the teacher to manage. Slack appears to be a little bit easier in that respect. 

Secondly, you may want to know how to sign up for our slack Channel.  [You will need to use this invitation:](https://join.slack.com/t/generalpsychology-hq/shared_invite/zt-hw53cjb8-Gu_GEolsoQNq2U7Q2CTvGg) (Links to an external site.)

A very important part about signing up for slack is that you need to use the email that you used to sign up for classes at North Seattle. The reason is that this will be a relatively easy way for me to make sure that the students enrolled in the class are able to access our slack Channel, and that random people cannot.

Once you have signed up for slack, spend some time filling out your profile make sure to make your profile picture and actual picture of you. And I believe every time from then on should you sign into slack, you'll see our abnormal psychology Channel.
 
The last thing about slack is that when it comes to sharing documents, you may need to add permissions for slack to interact with your word processing program. For instance I use Google Docs a lot and I have already added Google Docs as an app that is recognized by Slack.  Let me know which word processing program you use oh, it has to be a cloud-based, and I think I can add that to slack.  So far I've added Google Docs and Microsoft onedrive (both, I believe are free to use by North Seattle students.)

#### Tips for using Slack

[Slack tips, will need to sign in to canvas for this video](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ba5dc535-de92-40c7-9460-ac5301350a62){target='_blank'}

#### Adding yourself to a hidden slack channel

In Fall 2020, slack had a bug preventing the instructor from adding everyone to a channel with a single click.  This mean each person had to be added individually, which is very time consuming.  [This is a simple list of instructdions with pictures showing how to search then add yourself to a channel.](https://docs.google.com/document/d/1nH12L-FIFA2aXSMViuSt73WbAR9Fr78bQD0lpYTQLmg/edit?usp=sharing"){target='_blank'} 

## Access to OneDrive and email for students

I'm a fan of gmail and google drive, but as a fee-paying student in the Seattle Colleges District, you have been giving a free account with Microsoft oneDrive.  oneDrive is an online office suite that has web-based versions for email, word processing, spreadsheets, PowerPoints.  [here is where to go to set that up](https://itservices.seattlecolleges.edu/myseattlecolleges-login){target=’_blank’}

When you write a paper, you can write it directly into the word application in OneDrive, or you could write your paper on your home computer, and then as necessary upload into oneDrive.  

### Videos:  How to Log into and using oneDrive, Gmail

#### [Video how to log in to OneDrive--stored in canvas](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f92016e6-6dc6-4daa-a90c-ac4d013607a6){target='_blank'}

#### [Video how to generate a sharable link in OneDrive--stored in canvas](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f35b3b7d-331a-46e5-b308-ac4d013607e8){target='_blank'}

```{block, type='blueBackground'}
Please note that if you change the sharing settings, I think Microsoft creates a new URL that must be posted in our learning environment (slack, canvas, etc).  Again.  So, after you have set your sharing settings, copy the link and share it.   
```

#### [How to share a google drive doc -- stored in canvas](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0f8a111c-0346-4935-b556-ac4d013fed06){target='_blank'}

##### If Uploading a .doc(x) to google 

```{block,type='blueBackground'}
If you upload a word document into google docs, google will not convert it to a google doc format; instead it will maintain it as a .doc(x) file type because some users are just using google drive as a repository to share word docx.

But I can't leave feedback on those formats.

* So, after uploading the docx file, 

* right click the file and choose to 'open as a google doc'.

* Then, share that file with edit capabilities. 
```

#### [How to see google drive revisions -- stored in canvas](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2c3fcd6a-0ee9-4c97-9b71-ac4d013fed6b){target='_blank'}








# Week 4 Oct 17 {#Week4} 

## Read/watch the following

* [Module 7: Anxiety Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-7-anxiety-disorders/){target="_blank"}

* [humanistic intro](https://www.youtube.com/watch?v=KDRHaL6jyg8&list=PLDEwZwMNQswvPj4onxTjBdXgzFYJ6G-JJ&index=5){target="_blank"}

* [first 3 videos of this youtube playlist on biopsych](https://www.youtube.com/playlist?list=PLDEwZwMNQswtFvhRvOliHzeDfuBPIdsSf){target="_blank"}


## Do the following

* Pick an Anxiety disorder form the following: 
  +  panic
  +  phobia
  +  social anxiety disorder
  +  generalized anxiety Disorder

  * and find 2 articles that suggest what causes it
    * The article should be from either these two school databases:
      * [Academic Search Complete](https://libguides.northseattle.edu/az.php?a=a){target="_blank"}
      * [PsychArticles](https://libguides.northseattle.edu/az.php?a=p){target="_blank"}

* Write 1 or 2 paragraphs about what you have learned into your google doc.  This does not necessarily mean you should summarise the journal articles you found. This is a reflective piece.  Write about the questions you have or where your mind goes.

* Post a link in the week 4 channel

* Read 3 other student's work and engage them on their submission--you can ask them questions as an example. 

## Added material from "zoom lectures"

* Video [Introduction to Existential psychology](https://youtu.be/6eXnVhsz5qE){target='_blank'}, emphasis on @Yalom_Existential_Psychotherapy_1980

# Week 5 Oct 24 {#Week5} 

## 
## Do, Watch, and Read the following

A. Read [Module 5: stress Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-5-trauma-and-stressor-related-disorders/){target="_blank"}

B. Read Nancy Chick, [Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/){target="_blank"}

C. Read Alfie Kohn, [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/){target="_blank"}



## Do the following

1. Search for 3 reasonably competent definitions of trauma, but avoid the DSM.  You can use the DSM as a 4th source for contrast, if you want. Include references and do a quick summary/description of what you found. 
2. In the same document, how would you defend your answer to the statement:

>Everyone goes through trauma.

3. Post your paper in the #Stress channel.

4. Do A [self-reflection Survey](https://docs.google.com/forms/d/e/1FAIpQLSdCKXCNvH-nSdnuCz0OrFUcQPZXVEugR4D5lyBiZzNKYVkANw/viewform){target="_blank"}

    * The text boxes you see in this survey will expand to accommodate what you need to write. In other words, don’t feel like you must only say like 3 words to just fit the box shown.



```{block,type='blueBackground'}
<h4 style="text-decoration: underline;">Why write our research up?</h4>

For some of you, the invitation to join into a expert research conversation may still seem easy to decline but if you accept it you'll have to find a good question, search for sound data, formulate and support a good answer and then write it all up and even if you turn out a first-rate paper, it may be read not by anyone in the world but only by your teacher. And besides, you may think, my teacher knows all about my topic. What do I gain from writing up my research, other than proving I can do it?

One answer is that we write not just to share our work but to improve it before we do.

<h4 style="text-decoration: underline;">Write to remember</h4>

Experienced researchers first write just to remember what they read. A few talented people can hold in mind masses of information, but most of us get lost when we think about what *Smith found in light of Wong's position, and compare both to the odd data in Brunelli, especially as they are supported by Buscovich but what was it that Smith said?* When you don't take notes on what you read, you are likely to forget or, worse misremember it.

<h4 style="text-decoration: underline;">Write to understand</h4>

The second reason for writing is to see larger patterns in what you read. When you arrange and rearrange the results of your research in new ways, you discover new implications, connections, and complications. Even if you could hold it all in mind, you would need help to line up arguments that pull in different directions, plot out complicated relationships, sort out disagreements among experts. 

*I want to use these claims from long, but her argument is undercut by Smith's data. When I put them side-by-side, I see that Smith ignores this last part of Wong's argument. aha! If I introduce it with this part from Brunelli, I can focus on one more clearly. *

That's why careful researchers never put off writing until they've gathered all the data they need: they write from the start of their projects to help them assemble their information in new ways. 

<h4 style="text-decoration: underline;">Write to test your thinking</h4>

But even when they agree that writing is an important part of learning thinking and understanding some still wonder why they can't write up their research in their own way, why they have to satisfy demands imposed by a community that they have not joined, or even want to, and conform to conventions they did nothing to create. 

*Why should I adopt language in forms that are not mine? Aren't you just trying to turn me into an academic light yourself? If I write as you expect me to, I risk losing my identity.*

Such concerns are legitimate (most teachers wish students would raise them more often). But it would be a feeble education that did not change you at all, and the deeper your education the more it will change the "you" that you are or want to be.

That's why it is so important to choose carefully what you study and with whom. But it would be a mistake to think that learning to report sound research must threaten your true identity. It will change the way you think, but only by giving you more ways of thinking. You will be different by being freer to choose who you want to be and what you want to do with your life. 

But the most important reason for learning to write in ways readers expect is that when you write for others, **you demand more of yourself and when you write for yourself alone.** By the time you fix your ideas in writing, they are so familiar to you that you need help to see them not for what you want them to be *but for what they really are.* 

You will understand your own work better when you try to anticipate your readers inevitable and critical questions: how have you evaluated your evidence? Why do you think it's relevant? What ideas have you considered but rejected?
```

# Week 6 Oct 31{#Week6} 

```{block, type='instructorNote'}
On Thursday, May 12, there will be no classes held for the whole school.  

Faculty are expected to be doing other college work.  

Which means none of you can be required to attend any class on 5/12.  For any class.  In the whole Seattle college district.  
```


## Read the following

A. Nancy Chick, [Metacognition](https://cft.vanderbilt.edu/guides-sub-pages/metacognition/){target="_blank"}

B. Alfie Kohn, [The Case Against Grades](https://www.alfiekohn.org/article/case-grades/){target="_blank"}

C. Read/skim [Primer for Behaviorism and Semantic networks](https://docs.google.com/document/d/1MMziOQh7NjWRnrzCZDT99ArOu8Nv6CzQfTEfbSCzjYA/){target="_blank"}

* skim this but pay closer attention the semantic sections with the schematics for cars
* Think of a subject.  Maybe it's something academic like math, biology.  Maybe it's about sports, or in particular a single sport, like (the only one that matters) basketball.  
   * in what specific ways would the semantic network be different between a novice and expert?  I don't expect you to know technical terms here (like nodes, edges) but I want you to have an appreciation for how people may differ in terms of their networks

D. [Module 9: Obsessive and Hoarding disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-9-obsessive-compulsive-and-related-disorders/){target="_blank"}

## Do the following

 1. Pick one of the disorders in the OCD module: 
  
  * and find 2 articles that discusses its cognitive pattern
    * The article should be from either these two school databases:
      * [Academic Search Complete](https://libguides.northseattle.edu/az.php?a=a){target="_blank"}
      * [PsychArticles](https://libguides.northseattle.edu/az.php?a=p){target="_blank"}

 2. Write a page about what you have learned.  Write a summary, but write as if you were writing it to a non-technical person that doesn't understand cognitive psychology.  

 3. post a link in the [OCD channel](https://northseattlea-yus1991.slack.com/archives/C03EMV7UGKT){target="_blank"}

 4. Pick 2 other students and invite them to read your post. In the invitation, think about what you might like to receive some feedback about. 
    * Invite people to help you on any of the critical thinking standards, for example. 
    * if you are invited to give feedback, you don't have to.  Sometimes you might have several people asking for feedback.  Don't feel like you must respond to all of them.  
    Should you chose to give feedback, be kind and try to adhere to the request. 
    * Remember that they are trying things out and are sharing potentially vulnerable parts of their lives.  If you need help giving feedback, send your instructor a /dm and I can help.
    * Also, because it’s still the pandemic and everything is just hard, don’t fret if people you invite can’t respond. It’s likely that they are just overwhelmed with something.
    
 5. Post a re-write of one [or two] of your past written assignments.  Please choose assignments from work completed; if you didn't finish the synthesis paper, for example, don't use it here.   
    * Don't edit your original work.  Make a new entry in your One-google-doc to rule
    * use the channel [#re-write-self-reflection](https://northseattlea-yus1991.slack.com/archives/C03E2MD16RL){target="_blank"}
    * In the rewrite, you may want to use the critical thinking standards as a lens on your past work.  For instance, are there places you could be more deep in terms of complexity?  What research could inform how you think about your work from the textbook?  This is just a suggestion.


# Week 7 Nov 7 {#Week7} 

Stats and Depression and Bipolar

## read/watch

* [playlist of videos on depression and bipolar](https://www.youtube.com/playlist?list=PLDEwZwMNQswsr6gT7c0HT9rbpW5X-lstj){target="_blank"}

### Stats

[Intro to Histograms](https://youtu.be/qBigTkBLU6g?t=17){target="_blank"}

[Normal Distributions](https://youtu.be/rzFX5NWojp0?t=12){target="_blank"}

* Stat concepts
  * [Intro](https://youtu.be/Q5PT_Kb1Z-w){target="_blank"}  1 min
  * [Independent variable](https://youtu.be/Q5PT_Kb1Z-w?t=71){target="_blank"}  1 min
  * [Dependent variable](https://youtu.be/Q5PT_Kb1Z-w?t=108){target="_blank"} 1 min
  * [Central Tendency](https://youtu.be/Q5PT_Kb1Z-w?t=125){target="_blank"} 1 min
  * [Measure of Variation](https://youtu.be/Q5PT_Kb1Z-w?t=151){target="_blank"} 1 min
  * [Graphing/ Histograms](https://youtu.be/Q5PT_Kb1Z-w?t=196){target="_blank"} 1 min
  * [Examples of central tendency](https://youtu.be/Q5PT_Kb1Z-w?t=241){target="_blank"} 2 min
  * [Examples of variation](https://youtu.be/Q5PT_Kb1Z-w?t=312){target="_blank"} 1 min
  * [Examples of histogram](https://youtu.be/Q5PT_Kb1Z-w?t=382){target="_blank"} 1 min
  * [Normal Distributions](https://youtu.be/Q5PT_Kb1Z-w?t=436){target="_blank"} 5 min
  * [Null Hypotheses and Alpha](https://youtu.be/Q5PT_Kb1Z-w?t=737){target="_blank"} 1 min
  * [P-value](https://youtu.be/Q5PT_Kb1Z-w?t=817){target="_blank"} 3 min
  * [effect sizes & meta-analyses](https://youtu.be/Q5PT_Kb1Z-w?t=1025){target="_blank"} 3 min
  * [Three criteria to determine cause](https://youtu.be/Q5PT_Kb1Z-w?t=1230){target="_blank"} 1 min
  * [General Stat book contents](https://youtu.be/8MJvoliGils){target="_blank"} 1 min
  * [Correlations and linear regression](https://youtu.be/8MJvoliGils?t=50){target="_blank"} 5 min #at 2:43 I make a little bit of a mistake.  Technically, what is being presented on the slide are non-standardized scores. So though what I'm saying is correct, I should have further said, "once these scores are standardized, a change in 1 unit of X will increase Y by .63".
  * [linear regression output and coefficients](https://youtu.be/8MJvoliGils?t=259){target="_blank"} 5 min #Again, at 5:15, I make a mistake in the video.  The output is in un-standardized units and so the correct statement would be " this output is for unstandardized units, a movement up 1 unit on the x axis corresponds to an increase in the y axis about .13 units; had these variables been standardized, you would see the same value as the correlation, .63"
  * [Return of the P-value](https://youtu.be/8MJvoliGils?t=500){target="_blank"} 5 min but you might not find this helpful.  
 
  * [presentation slides can be found here](https://rpubs.com/briholt/abnormal_stats){target="_blank"}

### Brian's workflow video

I was asked to show how I might use tools to solve a question.  Here is a 36 minute video to that end. You might find it useful to see what I mean by "having a workflow" as a way to think critically.  But it's tedious.  Workflow isn't really exciting, so watch at 2x speeds and skip a lot. 

[Brian's workflow on whether Acute stress disorder is a good predictor of developing PTSD](https://youtu.be/y0V92Ggp0sc){target="_blank"}


## Do the following

* Search for a meta-analysis on a mood disorder (major, minor, persistent, bipolar (1,2) cyclothymia, dysthymia, or even the sub types of depression (e.g., Seasonal, postpartum)) and try to summarize the findings using your own words.  If you want to copy paste some of the language from the article, that is fine, but you should still try to use your own words to say it. 
  * here is [a video on how to find a meta-analysis in our library](https://youtu.be/8nmCpM2yi34){target="_blank"}

  * don't get lost in the details. I'm thinking this should not be more than 1 page, double spaced.  Aim for about 1/2 page of double spaced text. 
  
* Write down 5 questions about the methods of the paper.  How did they do the meta analysis?
 
* Put both writings (summary and questions) into the one document and post it in channel [#meta_analysis.](https://northseattlea-yus1991.slack.com/archives/C03FDQGM9M0){target='_blank'}

# Week 8 Eating Disorders Nov 14 {#Week8} 

* Make notice of the last week [final Project](#Week12).  I would recommend starting that, or at least putting in your list of things to do sooner than later.  

## Eating disorders

## Read 

* [textbook Eating Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-10-eating-disorders/){target='_blank'}

* [Read this excerpt from the PDM.2e](https://docs.google.com/document/d/18KIDPjn-xL48pphVnUrNr0rM3Ors4D1iDqgtr7QBMqs/edit?usp=sharing){target='_blank'} @lingiardiPsychodynamicDiagnosticManual2015a

## Do

* Write a few paragraphs on what, if any, is different between the two reading sources.
* Post your work to slack channel #eating

# Week 9  Psychotic Nov 21 {#Week9} 

* Make notice of the last week [final Project](#Week12).  I would recommend starting that, or at least putting in your list of things to do sooner than later.  

## Read 

* Schizophrenia videos
    * [Introduction.1  8 min](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a7387a2b-3da2-4723-a7e0-abd5011622b3){target='_blank'}
    * [Introduction.2  3  min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=770a8f9c-d5e1-4227-8574-abd501162fef){target='_blank'}
    * [Causes  9 min](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a7387a2b-3da2-4723-a7e0-abd5011622b3){target='_blank'}
    * [Schizophrenia Example 1  7 min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ea7c9382-0d68-4492-bb67-abd501162962){target='_blank'}
    * [Schizophrenia Example 2  10 min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5cf324e4-5d6a-403c-a1cb-abd50185b083){target='_blank'}


* [textbook psychotic Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-12-schizophrenia-spectrum-and-other-psychotic-disorders/){target='_blank'}

* [Skim necessary and sufficient](https://www.sfu.ca/~swartz/conditions1.htm){target='_blank'} @ConceptNecessaryConditions; most of this includes many examples. Go into the rabbit as far as you like, but at least try to doodle a grid of necessary/sufficient examples
* [Read **just** the abstract of](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3181977/){target='_blank'} @jablenskyDiagnosticConceptSchizophrenia2010, but read that abstract with diligence to word choices.  Have a dictionary handy and be sure to capture the meaning as well as the emotional/intentional nature of what was written.  Notice the year published
* Read Wikipedia's introduction to schizophrenia on @CausesSchizophrenia2020
* Read the introductory remarks of the Wikipedia entries; first an older version on the [Causes of schizophrenia (old)](https://en.wikipedia.org/w/index.php?title=Risk_factors_of_schizophrenia&oldid=1000718110){target='_blank'} and then the more recent version [Risk factors for schizophrenia](https://en.wikipedia.org/wiki/Risk_factors_of_schizophrenia){target='_blank'}
    * by the way, the reason I'm showing both of these is partly to show why relying on URL's is a mistake (URLs change)

* Read @harveyDualTaskInformationProcessing2006

## Do

* Write a short response to your thoughts about what you've read this week.  Keep it simple. Think about what strikes you as important.  
* post to slack channel #psychotic
* This week is heavier on reading, and less on writing.  But writing does improve our thinking.  You can always include your notes.

# Week 10 Personality Dis. Nov 28 {#Week10} 

* Make notice of the last week [final Project](#Week11).  I would recommend starting that, or at least putting in your list of things to do sooner than later.  

## Read/watch

[Textbook personality Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-13-personality-disorders/){target='_blank'} #make note of the therapy options for Borderline

* [PDM on Personality levels](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8d9d4140-098d-45c5-ae91-abd7013ff9f0){target='_blank'}  #this and the next few links will take you to panopto/canvas
  1) supporting file [Levels of organization](https://canvas.northseattle.edu/courses/2205994/files/192518784){target='_blank'}
  2) supporting file [Personality Disorder examples from PDM](https://canvas.northseattle.edu/courses/2205994/files/192518785){target='_blank'}

* read [@westenEfficacyDialecticalBehavior2006]  [link to source in slack](https://northseattlea-yus1991.slack.com/files/U03A8LDQV4Z/F03G6RHHGLE/westen2006.pdf){target='_blank'}
  * Note the date
  * For 2.5 pages it is dense. Jot down 2 major ideas.  You may need summarize in your own words to step up and above the details.  
  * Make a few notes on the motivation of the author
 
* [follow up study example](https://acamh.onlinelibrary.wiley.com/doi/full/10.1111/jcpp.13077?casa_token=mOamZoqXZS4AAAAA%3A1srQWWBtGfy14Zt2imV1539TfVzoDefV8wgNPwmck7xR_z1vQEscq9U3Y8_s16E2mrs_7ZfX5Qwlra7ejg){target="_blank"}


## Do

* Recall the 4 D's.  Write a response to the following:  In diagnosing a personality disorder what are some obstacles and or features to consider to differentiate them from healthy personalities? 

* If you want, I'd love to read articles that have a follow up analysis more than 6 months on DBT effectiveness.  (So, study therapy concludes with participants, maybe they do a 2 month follow up.  I'm looking for something more than 6 months.  Longer is better.)

* Post to slack channel [#personality](https://northseattlea-yus1991.slack.com/archives/C03H351K9LY){target="_blank"}

# Week 11 BIPOC, psychopathology, and final paper Dec 5 {#Week11}

Psychology has a problematic history of being weird.  That is:  W. E. I. R. D.
Western, educated, industrialized, rich, and democratic

I would also say tends to be white and it is worth being thoughtful about looking at mental disorders through the lens of people who do not fall under the weird acronym.

So one thing we can do is take some time to look at how Mental Health is different for Bipoc people

## Read/research some stuff

This is somewhat open ended. I have a lot of ignorance about this. And so rather than me dictating to you about how you should go about researching issues by bipoc, ethnicity, diversity and equity in abnormal psychology, I want you to think about this as an opportunity to teach me, your instructor, about some things.

Still, to help get started, here are some concepts you may want to search for; and you may want to combine them in a Google Scholar search, or maybe even just a general Google search.

* Any key word that is related to ethnicity or diversity could be searched for alongside of the psychological term dealing with 'mental health', like 'abnormal psychology', Psychopathology, etc.

* You might consider looking at statistics of mental Health for people in certain demographics, you might want to do the same thing or all of the above for particular disorders.

* [As a way to support students in evaluating their own work, consider this document, a rubric!, that talks about quality of thinking/writing without the points.](https://docs.google.com/document/d/1DRobbPDaLLLg-kSpeh95spS8tBoPvlK7lBFqvfrzHEk/edit?usp=sharing){target="_blank"} 


## Do some stuff

1) Outline your process that takes advantage of your workflow.

  * Write down your wants and intentions
    * eg., "I don't understand how indigenous Americans struggle with alcohol."  "What are the suicide rates for black people in the U.S.?"
  * What information do you need to move?
    * Wikipedia?
    * stats/frequencies?
  * What information is still missing?
    * it can be sufficient to just list these things.  Not all questions have been answered.  Not all questions have even been asked.  So don't feel like if you can't find some answer that you are doing something wrong.  

2) Summarize your readings/findings

3) Identify 2 or 3 actions/concepts that seem significant for others to know

4) Post your work to the [#Diversity channel](https://northseattlea-yus1991.slack.com/archives/C03FYPYSGG7){target="_blank"}


# "Week 12" cleaning up Dec 12 {#Week12}

## Do some stuff

1. [Final project](https://docs.google.com/document/d/11GxIlOTqrcXQ-MlW9eikqR-dH_ErgsjCv8xu0Zj5S60/edit?usp=sharing){target="_blank"}

  * [As a way to support students in evaluating their own work, consider this document, a rubric!, that talks about quality of thinking/writing without the points.](https://docs.google.com/document/d/1DRobbPDaLLLg-kSpeh95spS8tBoPvlK7lBFqvfrzHEk/edit?usp=sharing){target="_blank"}

2. [Final Self-reflection](https://forms.gle/VhfLKCBMugfDJuy18){target="_blank"}

3. [All work should be completed by end of day, December 12, 2021](https://northseattle.edu/calendars/academic-calendar?trumbaEmbed=view%3Devent%26eventid%3D559538082){target="_blank"}

4. Post your final to the [#Final channel](https://northseattlea-yus1991.slack.com/archives/C03GFMRCMHS){target="_blank"}

```{block, type='blueBackground'}

When searching for articles, be sure to track/take note of your search terms and combinations.  

This is important to save time.  It is not uncommon to accidentally lose articles and so you must go back and re-search.  Having no record of search terms may mean you have to recreate that history and it's time consuming.  
```
Be finished by December 12 17, 5pm (technically the last business day of the the last day of the quarter)

Don't be too stressed about this assignment name. It still follows the same format of read/do stuff but I have a few more instructions that take up space.  I thought I'd try a link out to it rather than embed it. 






`r if (knitr:::is_html_output()) '
# References {-}
'`