---
title: "Week 11"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---


# Week 11 June 12; BIPOC and other underrepresented groups, psychopathology, and final paper  {#Week11}

Psychology has a problematic history of being weird.  That is:  W. E. I. R. D.
Western, educated, industrialized, rich, and democratic.  We should also add Cis.  Doesn't fit easily in the 'Weird' acronym. 

I would also say tends to be white and it is worth being thoughtful about looking at mental disorders through the lens of people who do not fall under the weird acronym.

So one thing we can do is take some time to look at how Mental Health is different non White, non weird, non cis. 

## Read/research some stuff

This is somewhat open ended. I have a lot of ignorance about this. And so rather than me dictating to you about how you should go about researching issues of bipoc, ethnicity, diversity and equity in abnormal psychology, I want you to think about this as an opportunity to teach me, your instructor, about some things.

Still, to help get started, here are some concepts you may want to search for, and you may want to combine them in a Google Scholar search, or maybe even just a general Google search.


* Any key word that is related to ethnicity or diversity could be searched for alongside of the psychological term dealing with 'mental health', like 'abnormal psychology', Psychopathology, etc.

* Some terms that are considered offensive today were often used to describe people just 10, 20, 30 years ago.  So, if you do any historical perspectives, you might have to search using terms that feel unnatural. 

* You might consider looking at statistics of mental Health for people in certain demographics, you might want to do the same thing or all of the above for particular disorders.


###  A rubric to help evaluate critical thinking

* [As a way to support students in evaluating their own work, consider this document, a rubric!, that talks about quality of thinking/writing without the points.](https://docs.google.com/document/d/1DRobbPDaLLLg-kSpeh95spS8tBoPvlK7lBFqvfrzHEk/edit?usp=sharing){target="_blank"} 


## Do some stuff

1) Outline your process that takes advantage of your workflow.

  * Write down your wants and intentions
    * eg., "I don't understand how indigenous Americans struggle with alcohol."  "What are the suicide rates for black people in the U.S.?"
  * What information do you need to move?
    * Wikipedia?
    * stats/frequencies?
  * What information is still missing?
    * it can be sufficient to just list these things.  Not all questions have been answered.  Not all questions have even been asked.  So don't feel like if you can't find some answer that you are doing something wrong.  

2) Summarize your readings/findings

3) Identify 2 or 3 actions/concepts that seem significant for others to know

4)

  * [As a way to support students in evaluating their own work, consider this document, a rubric!, that talks about quality of thinking/writing without the points.](https://docs.google.com/document/d/1DRobbPDaLLLg-kSpeh95spS8tBoPvlK7lBFqvfrzHEk/edit?usp=sharing){target="_blank"}

5. [Final Self-reflection](https://forms.gle/VhfLKCBMugfDJuy18){target="_blank"}

6. All work should be completed by end of day, June 15, 2023

7. Post your work to the [#week11](https://spr23abnormalpsych.slack.com/archives/C058TATKMEG){target="_blank"}

Don't be too stressed about this assignment name. It still follows the same format of read/do stuff but I have a few more instructions that take up space.  I thought I'd try a link out to it rather than embed it. 




`r if (knitr:::is_html_output()) '
# References {-}
'`