---
title: "Week 9"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---


# Week 9  Psychotic Nov 20 {#Week9} 

* Make notice of the last week [final Project](#Week11).  I would recommend starting that, or at least putting in your list of things to do sooner than later.  

## Read 

* Schizophrenia videos
    Intro #1 will be in class
    
    * [Introduction.2  3  min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=770a8f9c-d5e1-4227-8574-abd501162fef){target='_blank'}
    * [Causes  9 min](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a7387a2b-3da2-4723-a7e0-abd5011622b3){target='_blank'}
    * [Schizophrenia Example 1  7 min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ea7c9382-0d68-4492-bb67-abd501162962){target='_blank'}
    * [Schizophrenia Example 2  10 min ](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5cf324e4-5d6a-403c-a1cb-abd50185b083){target='_blank'}


* [textbook psychotic Disorders](https://opentext.wsu.edu/abnormal-psych/chapter/module-12-schizophrenia-spectrum-and-other-psychotic-disorders/){target='_blank'}

* [Skim necessary and sufficient](https://www.sfu.ca/~swartz/conditions1.htm){target='_blank'} @ConceptNecessaryConditions; most of this includes many examples. Go into the rabbit as far as you like, but at least try to doodle a grid of necessary/sufficient examples
* [Read **just** the abstract of](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3181977/){target='_blank'} @jablenskyDiagnosticConceptSchizophrenia2010, but read that abstract with diligence to word choices.  Have a dictionary handy and be sure to capture the meaning as well as the emotional/intentional nature of what was written.  Notice the year published
* Read Wikipedia's introduction to schizophrenia on @CausesSchizophrenia2020
  * First read the introductory remarks of the Wikipedia entries; first an older version on the [Causes of schizophrenia (old)](https://en.wikipedia.org/w/index.php?title=Risk_factors_of_schizophrenia&oldid=1000718110){target='_blank'} and then the more recent version [Risk factors for schizophrenia](https://en.wikipedia.org/wiki/Risk_factors_of_schizophrenia){target='_blank'}
    * by the way, the reason I'm showing both of these is partly to show why relying on URL's for references can be a mistake (URLs change).

* Read @harveyDualTaskInformationProcessing2006 . The link in 2006 takes you to the reference section below.  You'll need to use that reference information to obtain the full text, which can be found in our library database PsychArticles. So, [go to the library article page.](https://libguides.northseattle.edu/welcome/articles){target='_blank'}  

## Do

* Write a short response to your thoughts about what you've read this week.  Keep it simple. Think about what strikes you as important.  
* post to [#week9 Discussion](https://canvas.seattlecolleges.edu/courses/16722/modules/items/780095){target="_blank"}
* This week is heavier on reading, and less on writing.  But writing does improve our thinking.  You can always include your notes.
* [Do A self-reflection Survey--be sure to seelct week 9 self-reflection](https://docs.google.com/forms/d/e/1FAIpQLSdCKXCNvH-nSdnuCz0OrFUcQPZXVEugR4D5lyBiZzNKYVkANw/viewform?usp=sf_link){target="_blank"}  


`r if (knitr:::is_html_output()) '
# References {-}
'`