---
title: "Week 3"
author: "bh"
date: "`r Sys.Date()`"
output: 
  html_document:
    css: "style.css"
link-citations: yes
bibliography: Abnormal_references.bib
biblio-style: apalike
---



# Week 3 Oct 9 {#Week3} 

```{block, type='blueBackground'}
Although we aren't using canvas, a few videos I've made are stored in Panopto.  I don't think you need to log into canvas for them to work.  But you may be prompted.
```

## Read the following

* [Module 3: Clinical Assessment, Diagnosis, and Treatment](https://opentext.wsu.edu/abnormal-psych/chapter/module-3-clinical-assessment-diagnosis-and-treatment/){target="_blank"}


* Not So Fast, a comment to Riskind about diagnostic schemes. @efran_not_2019  * [link to canvas file](https://canvas.seattlecolleges.edu/courses/16722/files?preview=13561289){target='_blank'}


* [Instructor Lecture Intro to Epidemiology](https://youtu.be/eUYIwNChS0I){target='_blank'}

* [Instructor Lecture Epidemiology Example](https://youtu.be/XQoH5avTlzA){target='_blank'}

* Intro to alternative to DSM
  * [Video on Psychodynamic Diagnostic Manual
](https://northseattle.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ed980a00-805e-4e8b-b5b2-ac4e014ff5fb){target='_blank'}  This link should take you to a video that should work. If not, say something in the logistics channel. 
  * [Skim Excerpts of Chapter 1 and 2 from PDM2 @lingiardiPsychodynamicDiagnosticManual2015a; stored slack](https://canvas.seattlecolleges.edu/courses/16722/files?preview=13561288){target='_blank'}  This should take you to a particular post in #resources in slack. 
     * In particular the Table on mental functioning
  * [Skim Example Personality disorders from PDM2; stored in canvas](https://canvas.seattlecolleges.edu/courses/16722/files?preview=13561290){target='_blank'}  This should take you to a particular post in #resources in slack. 
  
After reading/watching the above...

## Do the following

1. In the one document to rule them all, write about which psychology Model from ch2 resonates with you and why.

2.  Ask chatGpt what makes a good diagnostic system. Start in the abstract. Ask it about "criteria". Keep on the lookout for terms like "specificity" and "sensitivity".  From here, find some questions in it's responses and ask it to elaborate, to challenge it. Share your questions in your one google doc.

3. In your google doc, write a short essay about what you learned from chatGpt and any other source regarding diagnostic decision making. 

4. Lastly, in the one document to rule them all, list some questions about the readings/content for this week. Things you would like to learn more about. 

5. Post to [#week3](https://canvas.seattlecolleges.edu/courses/16722/discussion_topics/158848){target="_blank"}







`r if (knitr:::is_html_output()) '
# References {-}
'`